### ISSUE TITLE
libuavcan for C2000 - "C"

### ISSUE THREAD

**Issue by karu2003** [UAVCAN/libuavcan#102]
Good afternoon All.
I have a project of the Motor Controller at C2000 with InstaSpin FOC. Tell me where to start to make UAVCAN. I have the project  on a ANSI "C"(only). Now I have realized CANOpen (CANFestival). I want to make my drone. Did not choose where to change to add UAVCAN to the controller or CANOpen in ArduPilot.

Thank you
Andrew.

**Comment by pavel-kirienko** [comment]
Hi Andrew,

Since your project is implemented in C, you have two options:

- Convert to C++ and use libuavcan. Beware that libuavcan takes a lot of ROM (I predict that it will need around 30~40 KB in your case)
- Use libcanard. Libcanard is implemented in C99, it is very simple and has a very small memory footprint (both ROM and RAM). The back side is that it's a bit harder to use - this is the cost of its simplicity. The following resources will help you to get started:
  - [Demo application](https://github.com/UAVCAN/libcanard/blob/master/tests/demo.c).
  - [STM32 drivers](https://github.com/UAVCAN/libcanard/tree/master/drivers/stm32); use this as a reference while implementing your own driver for C2000. Please consider submitting your driver upstream, that would be highly appreciated!
  - [Another application, a more involved one](https://github.com/Zubax/zubax_chibios/blob/bootloader_specific_improvements/zubax_chibios/bootloader/loaders/uavcan.hpp).

I will be submitting some minimal documentation for Libcanard to uavcan.org soon, make sure to check it too.

Please address further questions either to the [mailing list](https://groups.google.com/forum/#!forum/uavcan) or to the [chat room](https://gitter.im/UAVCAN/general), thanks!
